### ISSUE TITLE
client module run problem

### ISSUE THREAD

**Issue by mushtu** [santoshjoshi/camel-cxfrs-example#3]
The client module gives me below exception:
Exception in thread "main" org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [cxf-services.xml]
Offending resource: class path resource [camel-context.xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 24 in XML document from class path resource [cxf-services.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 73; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'jaxrs:client'.
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)
...

**Comment by santoshjoshi** [comment]
Thanks a lot @mushtu for pointing out the issues. 

This has been resolved now

**Problem:**
  Migration to CXF 3.0 was creating the problem:

**Fix:** 
-  Added cxf-rt-rs-client module
-  jaxrs:client elements for injecting proxies have had the namespace changed from from "http://cxf.apache.org/jaxrs" to "http://cxf.apache.org/jaxrs-client".


**References**:
 - http://cxf.547215.n5.nabble.com/jaxrs-client-configuration-throws-error-td5740873.html
 - http://cxf.apache.org/docs/jax-rs.html#JAX-RS-FromCXF2.7.xtoCXF3.0.0
